config/routes.rb
Rails.application.routes.draw do
  get 'terms_conditions/index', as: :terms_conditions
  get 'business_profile_attachments/index'
  get 'business_profile_attachments/new'
  get 'business_profile_attachments/edit'
  get 'business_profile_attachments/show'
  get 'business_profile_attachments/destroy'
  get 'policies/terms_conditions', as: :privacy_policy
  get 'search/index', as: :search
  get 'search/result', as: :search_result
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'products/role_products', as: :role_products
  get 'products/products_from_individuals', as: :products_from_individuals
  get 'products/user_products', as: :user_products
  root 'index#index'
  get 'contact/index'
  get 'business_profiles/public_show/:id' => 'business_profiles#public_show', as: :business_profile_public_show
  get 'consumer_profiles/public_show/:id' => 'consumer_profiles#public_show', as: :consumer_profile_public_show
  devise_for :users, controllers: { registrations: "registrations" }
  resources :after_signup
  resources :consumer_profiles
  resources :business_profiles
  resources :shops
  resources :products
  resources :product_pictures
  get 'product_pictures/show_large/:id' => 'product_pictures#show_large', as: :product_picture_show_large
  resources :comments

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @search_term = SearchTerm.new
  end

  def result
    unless params.blank? or (not defined? params[:search_term][:term])
      @search_term = SearchTerm.new(search_term_permitted_params)
      @pg_search_documents = PgSearch.multisearch(params[:search_term][:term])
    else
      @search_term = SearchTerm.new
      render :result
    end
  end

  protected
    def search_term_permitted_params
      params.require(:search_term).permit(:term)
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.haml
%h1
  Search
= render 'partials/search/form', serach_term: @search_term

app/views/search/result.html.haml
= render 'partials/search/form', serach_term: @search_term
%h1
  Result(s)
- unless @pg_search_documents.blank?
  .row
    - @pg_search_documents.each do |pg_search_document|
      .col-sm-2
        - if pg_search_document.searchable.instance_of?(Product)
          .shop-image-wrapper
            .single-shops
              .shopinfo
                - if pg_search_document.searchable.product_pictures
                  - if pg_search_document.searchable.product_pictures.cover_image
                    - if pg_search_document.searchable.product_pictures.cover_image.first
                      - if (pg_search_document.searchable.product_pictures.cover_image) && (pg_search_document.searchable.product_pictures.cover_image.first.picture)
                        = link_to image_tag(pg_search_document.searchable.product_pictures.cover_image.first.picture_url(:thumb)), product_path(pg_search_document.searchable)
                      - else
                        = link_to image_tag(image_path("#{Defaults::NO_IMAGE}")), product_path(pg_search_document.searchable)
                .text-center
                  .title
                    %i
                      = link_to truncate(pg_search_document.searchable.name, :length => Defaults::PRODUCT_NAME_LENGTH_TILL), product_path(pg_search_document.searchable)
                  .details
                    =truncate(pg_search_document.searchable.description, :length => Defaults::PRODUCT_DESCRIPTION_LENGTH_TILL)

        - elsif pg_search_document.searchable.instance_of?(Shop)
          .shop-image-wrapper
            .single-shops
              .shopinfo
                - if pg_search_document.searchable.picture
                  = link_to image_tag(pg_search_document.searchable.picture_url(:thumb)), shop_path(pg_search_document.searchable)
                - else
                  = link_to image_tag(image_path("#{Defaults::NO_LOGO}")), shop_path(pg_search_document.searchable)
                .text-center
                  .title
                    %i
                      = link_to truncate(pg_search_document.searchable.name, :length => Defaults::SHOP_NAME_LENGTH_TILL), shop_path(pg_search_document.searchable)
                  - unless pg_search_document.searchable.business_types.blank?
                    .contact
                      %em
                        Type(s) of business:
                        %br
                        = pg_search_document.searchable.business_types.map { |business_type| business_type.name }.join ','
                  .details
                    =truncate(pg_search_document.searchable.description, :length => Defaults::SHOP_DESCRIPTION_LENGTH_TILL)
- else
  .row
    .col-sm-12
      No search result found!