config/routes.rb
Rails.application.routes.draw do
  get 'terms_conditions/index', as: :terms_conditions
  get 'business_profile_attachments/index'
  get 'business_profile_attachments/new'
  get 'business_profile_attachments/edit'
  get 'business_profile_attachments/show'
  get 'business_profile_attachments/destroy'
  get 'policies/terms_conditions', as: :privacy_policy
  get 'search/index', as: :search
  get 'search/result', as: :search_result
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'products/role_products', as: :role_products
  get 'products/products_from_individuals', as: :products_from_individuals
  get 'products/user_products', as: :user_products
  root 'index#index'
  get 'contact/index'
  get 'business_profiles/public_show/:id' => 'business_profiles#public_show', as: :business_profile_public_show
  get 'consumer_profiles/public_show/:id' => 'consumer_profiles#public_show', as: :consumer_profile_public_show
  devise_for :users, controllers: { registrations: "registrations" }
  resources :after_signup
  resources :consumer_profiles
  resources :business_profiles
  resources :shops
  resources :products
  resources :product_pictures
  get 'product_pictures/show_large/:id' => 'product_pictures#show_large', as: :product_picture_show_large
  resources :comments

end

app/views/partials/common/_business_profile_form.html.haml
.row
  .col-sm-12
    = business_profile.text_field :contact_person, autofocus: true, class: 'simple-tooltip', title: "Full name of the contact person."
    = business_profile.text_field :helpline, class: 'simple-tooltip', title: "Help line."
    = business_profile.text_field :website, class: 'simple-tooltip', title: "Website url, if any"
    = business_profile.text_area :address, class: 'simple-tooltip', title: "Address of the office where people can contact."
    = business_profile.text_field :phone, class: 'simple-tooltip', title: "Phone"
    = business_profile.text_field :mobile, class: 'simple-tooltip', title: "Mobile"

  .row
    .col-sm-12.col-center-block
      #busines_profile_attachments.row
        = business_profile.fields_for :business_profile_attachments, :wrapper => false do |business_profile_attachment|
          .col-sm-6
            = render 'partials/business_profile_attachments/nested_form', business_profile_attachment: business_profile_attachment

  .row
    .col-md-12
      .button-group
        = business_profile.link_to_add :business_profile_attachments, :class => "add_nested_fields btn btn-primary btn-raised", :data => { :target => "#busines_profile_attachments" } do
          %i.mdi-content-add-box
          Add document as attachment
        = business_profile.submit(value='Update profile information', class: 'btn btn btn-primary btn-raised pull-right')

app/views/partials/common/_consumer_profile_form.html.haml
.row
  .col-sm-12
    = consumer_profile.text_field :name, autofocus: true, class: 'simple-tooltip', title: "Consumers' full name."
    = consumer_profile.text_area :address, class: 'simple-tooltip', title: "Address"
    = consumer_profile.text_field :phone, class: 'simple-tooltip', title: "Phone"
    = consumer_profile.text_field :mobile, class: 'simple-tooltip', title: "Mobile"
    = consumer_profile.submit(value='Update profile information', class: 'btn btn btn-primary btn-raised pull-right')

app/views/partials/common/_shop_form.html.haml
.row
  .col-md-6
    = shop.text_field :name, autofocus: true, class: 'simple-tooltip', title: "Put your original shop name here. This will be visible when someone enter the shop."
    = shop.text_field :sub_domain, class: 'simple-tooltip', title: "Choose your sub-domain. It will be applicable for your shop."
    = shop.text_area :description, class: 'simple-tooltip', title: "Describe about your shop. The more and appropiate description you will add, the more customer will visit to your shop."
    = shop.collection_select :business_type_list, Shop.get_business_types, :name, :name, {selected: @shop.business_types.map(&:name)}, {:multiple => true, :style => "width:100%;"}
  .col-md-6
    = shop.text_area :address, class: 'simple-tooltip', title: "Type address. User may like to buy directly from your shop!"
    = shop.text_field :mobile, class: 'simple-tooltip', title: "So that user can contact with the person who is available to the shop 24x7."
    = shop.text_field :trade_license, :label=>"Trade License", class: 'simple-tooltip', title: "It will be needed to varify your shop in near future."
    = shop.text_field :national_id, :label=>"National ID", class: 'simple-tooltip', title: "Shop owners personal identity."

  .row
    .col-sm-12.col-center-block
      #shop_attachments.row
        = shop.fields_for :shop_attachments, :wrapper => false do |shop_attachment|
          .col-sm-6
            = render 'partials/shop_attachments/nested_form', shop_attachment: shop_attachment

  .row
    .col-md-12
      = shop.file_field :cover_photo, class: 'simple-tooltip', title: "Upload cover photo for shop. It will needed in the fron-page of shop."
      = shop.hidden_field :cover_photo_cache
      - if @shop.cover_photo?
        = image_tag(@shop.cover_photo_url, class: 'img-responsive')
      - else
        = image_tag(image_path("#{Defaults::NO_IMAGE}"))

  .row
    .col-md-12
      = shop.file_field :picture, :label=>"Logo", class: 'simple-tooltip', title: "Upload logo of your shop/business."
      = shop.hidden_field :picture_cache
      - if @shop.picture?
        = image_tag(@shop.picture_url)
      - else
        = image_tag(image_path("#{Defaults::NO_IMAGE}"))

      - if @shop.id.nil?
        = shop.check_box :terms_conditions, :label=>"I agree to the #{link_to 'Terms and Conditions', terms_conditions_path, target: :_blank}.".html_safe, class: 'simple-tooltip', title: "You have to agree with the terms and conditions."

  .row
    .col-md-12
      .button-group
        = shop.link_to_add :shop_attachments, :class => "add_nested_fields btn btn-primary btn-raised", :data => { :target => "#shop_attachments" } do
          %i.mdi-content-add-box
          Add document as attachment
        = shop.submit(value='Create Shop', class: 'btn btn btn-primary btn-raised')